spring:
  application:
    name:
      idea-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://my_keycloak:8080/realms/sandbox
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://postgres:5432/ideas_db
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: validate
      show-sql: 'true'

server:
  port:
    8082
eureka:
  client:
    service-url:
       defaultZone: http://eureka-server:8761/eureka
logging:
  file:
    name: /Users/daurenassanbaev/IdeaProjects/microservices/idea-service/logs/idea-service-logs.log
