spring:
  application:
    name:
      ratings-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://my_keycloak:8080/realms/sandbox
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://postgres:5432/ratings_db
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: validate
      show-sql: 'true'
  kafka:
    bootstrap-servers: my_kafka:9092

server:
  port:
    8085
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
logging:
  file:
    name: /Users/daurenassanbaev/IdeaProjects/microservices/ratings-service/logs/ratings-service-logs.log

