spring:
  application:
    name:
      amazon-s3-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
#accesskey:
#secret:
bucketName:
  daurenassanbaevfiles
region:
  eu-north-1
application:
  bucket:
    name: daurenassanbaev
server:
  port:
    9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  file:
    name: /Users/daurenassanbaev/IdeaProjects/microservices/amazon-s3-service/logs/amazon-s3-service-logs.log
